name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust Java version as per your project

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.EC2_HOST }}  # EC2 instance IP or DNS
          port: ${{ secrets.EC2_PORT }}    # SSH port
          username: ${{ secrets.EC2_USERNAME }}  # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}     # SSH private key
          local_path: 'target/your-app.jar'       # Path to your built JAR
          remote_path: '/path/on/ec2/'             # Remote directory on EC2
