name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust Java version as per your project
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          REMOTE_HOST: ${{ secrets.EC2_HOST }}  # EC2 instance IP or DNS
          REMOTE_PORT : ${{ secrets.EC2_PORT }}    # SSH port
          REMOTE_USER : ${{ secrets.EC2_USERNAME }}  # SSH username
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}     # SSH private key
          SOURCE : 'target/clinic-0.0.1-SNAPSHOT.jar'       # Path to your built JAR
          TARGET : '/home/ec2-user/dentalden/bin/'             # Remote directory on EC2

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ec2-user/dentalden/bin/
            java -jar clinic-0.0.1-SNAPSHOT.jar
