name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust Java version as per your project
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy jar to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          REMOTE_HOST: ${{ secrets.EC2_HOST }}  # EC2 instance IP or DNS
          REMOTE_PORT : ${{ secrets.EC2_PORT }}    # SSH port
          REMOTE_USER : ${{ secrets.EC2_USERNAME }}  # SSH username
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}     # SSH private key
          SOURCE : 'target/clinic-0.0.1-SNAPSHOT.jar'       # Path to your built JAR
          TARGET : '/home/ec2-user/dentalden/bin/'             # Remote directory on EC2

      - name: Deploy script files to EC2
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          REMOTE_HOST: ${{ secrets.EC2_HOST }}  # EC2 instance IP or DNS
          REMOTE_PORT: ${{ secrets.EC2_PORT }}    # SSH port
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}  # SSH username
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}     # SSH private key
          SOURCE: '/run/'
          TARGET: '/home/ec2-user/dentalden/bin/'            # Remote directory on EC2
          SCRIPT_AFTER: /home/ec2-user/dentalden/bin/restart.sh

#      - name: Executing remote ssh commands
#        uses: msatbsx/ssh-and-run-your-script-on-remote-host@v0.1.1 # replace with current tag, avoid using main or latest
#        id: runner
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          user: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          command: |
#            cd /home/ec2-user/dentalden/bin/
#            java -jar clinic-0.0.1-SNAPSHOT.jar